/**
 * releases.ts — GENERATED by tools/changelog.mjs. Do not edit here.
 *
 * The source is CHANGELOG.md, and there is exactly one. Notes maintained
 * separately from the release drift from it, and the drift is invisible until a
 * reader is told about a change that is not in the build they are running.
 *
 * BOUNDED at 5: what changed, and four before it. A list that grows by
 * accumulation eventually becomes the app. Everything older lives at
 * {@link NOTES_PAGE}, which is a page in this app — never a link off to a code
 * host, because somebody who wants to know what changed in a maths trainer
 * should not land in a repository.
 *
 * Regenerate: node tools/changelog.mjs
 * Check: node tools/changelog.mjs --check   (runs on every commit)
 */

/** Which slot of the version moved, and therefore what kind of change it was. */
export type ReleaseKind = 'VERSION' | 'CAPABILITY' | 'ITERATION';

/** One release, in the words a reader would use for it. */
export interface Release {
  readonly version: string;
  readonly kind: ReleaseKind;
  /** What changed. Never empty. */
  readonly lines: readonly string[];
  /** What is still missing. Never empty either — see the generator's header. */
  readonly stillMissing: string;
}

/** How many releases the app carries: the current one plus four. */
export const MAX_SHOWN = 5;

/** The page the rest live on. A path in this app, never another site. */
export const NOTES_PAGE = '/whats-new';

/**
 * How many releases exist that are NOT in the list below.
 *
 * Carried so the app can say so. A panel showing five with no hint that there
 * are more implies five is all there has ever been, which is a small lie that
 * costs nothing to avoid.
 *
 * ANNOTATED `number` ON PURPOSE. Without it this infers the literal type of
 * whatever today's count happens to be, and the screen's branch on it becomes a
 * comparison between two literals — which type-checks while the count is one
 * value and fails the day it changes. It failed on the release that first made
 * it non-zero, which is also the first release on which that branch had ever
 * been reachable.
 */
export const OLDER_THAN_SHOWN: number = 4;

/** Newest first. */
export const RELEASES: readonly Release[] = [
  {
    version: '0.8.0',
    kind: 'CAPABILITY',
    lines: [
      'You can choose how the questions are set now. Pick a topic and it asks which kind of question you want before it starts.',
      'They have names rather than numbers, and the name says what the question does: cancelling units offers two steps, three steps or four steps; powers offers squares, then cubes and roots, then past a cube; significant figures offers one rule, either rule, then two rules in order. Every one of them is there the first time you open it. Nothing is locked, nothing has to be earned, and nothing switches you to a different one because of how a run went.',
      'Two topics were offering a choice that changed nothing. This is worth being plain about, because the setting has existed since the first release and every question you have ever been given came at the first one.',
      'When each was measured against the one below it, six of the fourteen steps produced questions nobody could tell apart — bigger numbers, and nothing else. So the topics now offer what they actually have. Proportions has one kind of question. Fractions has two. The other five have three each.',
      'Fractions can hand you the rate upside down. Instead of "the concentration is 4.00 mol/L" you get "the volume one mole takes up is 0.250 L/mol", and the first thing it asks is to turn that over. This is what the topic is named for and it had never once been asked.',
      'Cancelling units goes up to four conversions in a row, which is where the long chemistry questions live — a volume of liquid weighed, turned into moles, and then into particles or into the volume it fills as a gas.',
      'Two things were found while measuring all of this and both are fixed. A proportion question could ask you to work out a number that was already printed in the question, when a recipe took one mole of the first substance. And on a long conversion, turning one factor over and turning the whole chain over could come to the same answer, so being told which one happened would have been a guess.',
    ],
    stillMissing: 'nothing can be handed in and there is still no page for whoever set the work. Proportions has one kind of question because a second one means asking about two reactions in a row, and that is a question this has never posed — it is for whoever is teaching to ask for, not for this to decide. The icon is still a simple drawing rather than a proper one.',
  },
  {
    version: '0.7.0',
    kind: 'CAPABILITY',
    lines: [
      'You can practise one move on its own now, instead of working whole questions and walking past the step you want four times to reach it once.',
      'Whole questions are what makes a move stick once you have it. A move you do not have yet is built the other way round: by doing that one thing again. So there is a second way in — pick one of six moves and get that move, over and over, with the question around it for context but only the one step to answer.',
      'The six are choosing the move, isolating the unknown, scaling by a ratio, doing the arithmetic, carrying and cancelling units, and significant figures. Stop whenever you like; it tells you what happened and there is no number anywhere.',
      'Nothing about a practice run is stored. There is no session, nothing to hand in, and nothing written to the device.',
      'Three questions were asking for letters that were not in the equation. This is the one worth knowing about, and it had been there since the first release.',
      'A question would show you PV = nRT and then ask you to rearrange it for ng. Another showed n × M = m and offered you n = m ÷ (Mm). A third showed T(K) = T(°C) + 273.15 and called them TK and TC. Those were names used inside the app, and they were never meant to reach anybody. All of them now show the letters that are actually in the equation.',
      'And the answer choices could be read two ways. One option came out as V₁ = (P₁) ÷ P₂ × V₂, which could mean two different things depending on where you put the brackets — and neither of them was the mistake the option was supposed to represent. Brackets go where they change the meaning now, and nowhere else.',
      'Both of those were found by building the practice screen, because it is the first thing that ever showed one of those steps on its own.',
    ],
    stillMissing: 'every question still arrives at the same difficulty when you work a whole set. Nothing can be handed in and there is no page for whoever set the work. The icon is still a simple drawing rather than a proper one.',
  },
  {
    version: '0.6.0',
    kind: 'CAPABILITY',
    lines: [
      'It works with no connection now, which is the one that matters most for whoever is doing this on a bus, in a car, or somewhere the signal gives out halfway through.',
      'Open it once with a connection and it keeps a copy on the device. After that it opens whether or not there is any network at all — the questions, the marking, the explanations and the list of what changed. Nothing is ever fetched while you work, because nothing ever was: the questions are worked out on the device.',
      'And when a newer version arrives, it waits for you. This is the part most apps get wrong, so it is worth saying what happens instead.',
      'A newer version does not replace what you have while you are using it. You get a line at the top of the screen saying one is ready, with a button to switch to it and a button to leave it for later. Nothing reloads on its own, nothing is lost part-way through a question, and if you ignore it entirely you get the new one next time you open the app.',
      'If you have never opened this before, you are told none of that. There is nothing you missed.',
      'You can keep it on your home screen, and the information button now lists how to do that on each kind of device.',
      'Also: the panel that tells you which copy of the app is on the device now says so exactly, which matters because the version number on screen is reported by the code that is running — on an out-of-date copy, that is the old code reporting itself perfectly accurately.',
    ],
    stillMissing: 'there is still no way to practise a single move over and over, which is the thing most worth having when one particular step is the one going wrong. Every question still arrives at the same difficulty. Nothing can be handed in and there is no page for whoever set the work. And the icon is a simple drawing rather than a proper one.',
  },
  {
    version: '0.5.0',
    kind: 'CAPABILITY',
    lines: [
      'There is something to open. Until now everything in here worked and none of it could be seen.',
      'You get a short page saying what this is and what it is not, and then you pick one of the seven kinds of question and work through five of them, one step at a time. Get a step wrong and it tells you which mistake produces that exact number — and the step stays where it is until you get it, because a step you can walk past is just another question.',
      'It can be made easier to read, and those settings never leave your device. Bigger text, more space between letters and lines, showing one thing at a time, and reading the question aloud where the device can do that. None of them is written into anything you hand in and none of them is sent anywhere. That is deliberate rather than an oversight: what somebody needs in order to read something is nobody else\'s business, and a tool that quietly passed it on would make them disclose it every time they used it.',
      'Day and night colours, following the device unless you say otherwise. The colours were measured against a contrast standard before anything was drawn, in both, on every screen — including the ones that only appear after a wrong answer, which is where this kind of thing usually goes unchecked.',
      'An information button in the corner, with what this is, how to keep it on your home screen on each kind of device, where the questions come from, what it stores, what changed, the accessibility statement and the licence. The page you see first is moved in there when you press Start, so it is still reachable rather than gone.',
      'And a page listing every release, which the panel above links to. The panel itself never shows more than five, and says how many it is not showing.',
    ],
    stillMissing: 'it does not work offline yet — close the connection and it will not open, which is worst for exactly the people who need it on a bus. There is still no way to practise a single move over and over, which is the thing most worth having when one particular step is the one going wrong. Nothing can be handed in and there is no page for whoever set the work. Every question arrives at the same difficulty for now. And there is no way to be told when a newer version is waiting.',
  },
  {
    version: '0.4.0',
    kind: 'CAPABILITY',
    lines: [
      'When a new version arrives, this will be able to tell you what changed — and it will not be an endless list.',
      'Every app should say what is different since last time, in the place you already are, rather than sending you off to a website meant for programmers. This release builds the part that holds those words: the newest release plus four before it, and nothing older than that. Everything further back lives on a page inside the app itself.',
      'Five is a decision and not a number that happened. A list that grows by accumulation eventually becomes longer than the thing it is describing, and nobody opening a maths trainer wants to scroll through two years of it. The app also knows how many releases it is NOT showing, so it can say so, instead of leaving an impression that five is all there has ever been.',
      'The words are now written in one place and only one place. Until now, what a reader would see and what was kept alongside the working parts were two separate lists — and two lists drift, so an app ends up describing a change that is not in the version somebody is actually running. There is one set of words now, and a check refuses any change that lets the two disagree.',
    ],
    stillMissing: 'there is still no screen, so the panel that would appear on a new version, and the page it would open, do not exist yet. What exists is the list of words and the rule about how long it is allowed to be. Nothing here can be opened and read.',
  },
];
