/**
 * releases.ts — GENERATED by tools/changelog.mjs. Do not edit here.
 *
 * The source is CHANGELOG.md, and there is exactly one. Notes maintained
 * separately from the release drift from it, and the drift is invisible until a
 * reader is told about a change that is not in the build they are running.
 *
 * BOUNDED at 5: what changed, and four before it. A list that grows by
 * accumulation eventually becomes the app. Everything older lives at
 * {@link NOTES_PAGE}, which is a page in this app — never a link off to a code
 * host, because somebody who wants to know what changed in a maths trainer
 * should not land in a repository.
 *
 * Regenerate: node tools/changelog.mjs
 * Check: node tools/changelog.mjs --check   (runs on every commit)
 */

/** Which slot of the version moved, and therefore what kind of change it was. */
export type ReleaseKind = 'VERSION' | 'CAPABILITY' | 'ITERATION';

/** One release, in the words a reader would use for it. */
export interface Release {
  readonly version: string;
  readonly kind: ReleaseKind;
  /** What changed. Never empty. */
  readonly lines: readonly string[];
  /** What is still missing. Never empty either — see the generator's header. */
  readonly stillMissing: string;
}

/** How many releases the app carries: the current one plus four. */
export const MAX_SHOWN = 5;

/** The page the rest live on. A path in this app, never another site. */
export const NOTES_PAGE = '/whats-new';

/**
 * How many releases exist that are NOT in the list below.
 *
 * Carried so the app can say so. A panel showing five with no hint that there
 * are more implies five is all there has ever been, which is a small lie that
 * costs nothing to avoid.
 */
export const OLDER_THAN_SHOWN = 0;

/** Newest first. */
export const RELEASES: readonly Release[] = [
  {
    version: '0.4.0',
    kind: 'CAPABILITY',
    lines: [
      'When a new version arrives, this will be able to tell you what changed — and it will not be an endless list.',
      'Every app should say what is different since last time, in the place you already are, rather than sending you off to a website meant for programmers. This release builds the part that holds those words: the newest release plus four before it, and nothing older than that. Everything further back lives on a page inside the app itself.',
      'Five is a decision and not a number that happened. A list that grows by accumulation eventually becomes longer than the thing it is describing, and nobody opening a maths trainer wants to scroll through two years of it. The app also knows how many releases it is NOT showing, so it can say so, instead of leaving an impression that five is all there has ever been.',
      'The words are now written in one place and only one place. Until now, what a reader would see and what was kept alongside the working parts were two separate lists — and two lists drift, so an app ends up describing a change that is not in the version somebody is actually running. There is one set of words now, and a check refuses any change that lets the two disagree.',
    ],
    stillMissing: 'there is still no screen, so the panel that would appear on a new version, and the page it would open, do not exist yet. What exists is the list of words and the rule about how long it is allowed to be. Nothing here can be opened and read.',
  },
  {
    version: '0.3.0',
    kind: 'CAPABILITY',
    lines: [
      'Significant-figures questions can now mix adding and multiplying, which is the kind people get wrong most.',
      'Two rules govern how many digits an answer is allowed to keep, and they are different rules. Adding is limited by decimal places. Multiplying is limited by significant figures. A question that does both — add two measurements, then multiply by a third — needs both rules, in order, and the usual mistake is to skip the first one and round on the fewest digits in sight.',
      'Until now this app could not ask that question at all. It could only ask questions that used one rule or the other, so the hardest case in the topic was missing. It is there now, from the second difficulty level up, and it asks about the middle step on its own: how many significant figures is that sum entitled to? — without asking anyone to round it, because rounding partway through is the mistake, not the method.',
      'This was found by reading published research on what people actually get wrong, rather than by testing the app against itself. The app\'s own checks could never have found it: they only ever look at questions the app is able to ask.',
    ],
    stillMissing: 'there is no screen. Nothing here can be opened and used yet. Everything above lives in the part that works out the questions and marks the answers, and there is nothing to look at.',
  },
  {
    version: '0.2.1',
    kind: 'ITERATION',
    lines: [
      'Nothing this app says will ever suggest the problem is you.',
      'An app that fails to teach someone should leave them thinking that app did not work for me, not I cannot be taught. So none of the words in it talk about effort, or about what someone ought already to know, or call anything easy. Calling something easy leaves only one explanation for why it did not go well, and that explanation is the person reading it.',
      'This is now checked automatically every time the app changes, the same way the no-scores rule is, so it cannot quietly stop being true.',
    ],
    stillMissing: 'there is no screen, so none of these words have reached anybody yet. The check is in place for when they do.',
  },
  {
    version: '0.2.0',
    kind: 'CAPABILITY',
    lines: [
      'No scores, no streaks, no targets, and nothing congratulating anybody.',
      'A streak teaches you to protect a number, and it makes stopping feel like losing something. That is the opposite of what is useful for the person who most needs to sit and do twenty of these.',
      'What you get instead is what changed:',
      'A mistake made once is not a pattern, and nothing is said about it.',
      'Made twice, it turns up at the end.',
      'Made three times, it is named while you are still working — once, with what fixes it — and then not raised again.',
      'If you were making the same mistake and then you stopped, it says so. Only if that actually happened, and one right answer after a run of wrong ones is not enough to count.',
      'And if a whole set went wrong, it does not tell you how many. Four questions and none right is true and is no use to anybody. It says what the mistake was and that it is one thing to fix, not a pile of questions to do again.',
      'Also fixed: a multiple-choice question could mark the wrong option correct if it was one the marking had not been told about. On a rearranging question that meant the upside-down answer would have been accepted. Nobody could have run into this yet — there is no screen — but it would have been waiting.',
    ],
    stillMissing: 'there is no screen, so nothing above can be seen. And there is still no way to practise a single skill on its own, which is the thing most worth having if one particular move is the one going wrong.',
  },
  {
    version: '0.1.0',
    kind: 'CAPABILITY',
    lines: [
      'The first release. It works out questions and marks answers; there is nothing to look at yet.',
      'What it covers. Seven kinds of algebra, and only these seven, because each one is something you cannot do a chemistry calculation without: rearranging a formula, proportions and cross-multiplying, scientific notation, powers and roots, fractions and rates, cancelling units through a chain, and significant figures.',
      'What makes it different from a calculator. It does not just mark an answer wrong. It works out which mistake produces that exact number — the ratio used upside down, the exponent multiplied instead of raised, a conversion factor turned the wrong way — and says so.',
      'And it refuses to guess. If two different mistakes would produce answers you could not tell apart, the app will not ask that question at all. It would rather stay quiet than tell somebody they have a misunderstanding they may not have. When it genuinely cannot tell what happened, it says that too, rather than picking something plausible.',
    ],
    stillMissing: 'no screen, nothing to open, no way to practise a single skill on its own, and nothing to hand to anybody at the end.',
  },
];
