/**
 * releases.ts — GENERATED by tools/changelog.mjs. Do not edit here.
 *
 * The source is CHANGELOG.md, and there is exactly one. Notes maintained
 * separately from the release drift from it, and the drift is invisible until a
 * reader is told about a change that is not in the build they are running.
 *
 * BOUNDED at 5: what changed, and four before it. A list that grows by
 * accumulation eventually becomes the app. Everything older lives at
 * {@link NOTES_PAGE}, which is a page in this app — never a link off to a code
 * host, because somebody who wants to know what changed in a maths trainer
 * should not land in a repository.
 *
 * Regenerate: node tools/changelog.mjs
 * Check: node tools/changelog.mjs --check   (runs on every commit)
 */

/** Which slot of the version moved, and therefore what kind of change it was. */
export type ReleaseKind = 'VERSION' | 'CAPABILITY' | 'ITERATION';

/** One release, in the words a reader would use for it. */
export interface Release {
  readonly version: string;
  readonly kind: ReleaseKind;
  /** What changed. Never empty. */
  readonly lines: readonly string[];
  /** What is still missing. Never empty either — see the generator's header. */
  readonly stillMissing: string;
}

/** How many releases the app carries: the current one plus four. */
export const MAX_SHOWN = 5;

/** The page the rest live on. A path in this app, never another site. */
export const NOTES_PAGE = '/whats-new';

/**
 * How many releases exist that are NOT in the list below.
 *
 * Carried so the app can say so. A panel showing five with no hint that there
 * are more implies five is all there has ever been, which is a small lie that
 * costs nothing to avoid.
 *
 * ANNOTATED `number` ON PURPOSE. Without it this infers the literal type of
 * whatever today's count happens to be, and the screen's branch on it becomes a
 * comparison between two literals — which type-checks while the count is one
 * value and fails the day it changes. It failed on the release that first made
 * it non-zero, which is also the first release on which that branch had ever
 * been reachable.
 */
export const OLDER_THAN_SHOWN: number = 10;

/** Newest first. */
export const RELEASES: readonly Release[] = [
  {
    version: '0.14.0',
    kind: 'CAPABILITY',
    lines: [
      'A set you were given is still there if you close it. Shut the tab, let the device sleep, come back later — the app offers to pick it up at the step it stopped on, with everything already done still counted.',
      'Only a set somebody gave you is remembered. Practice is not, because practice records nothing, and there is nothing in a practice run to lose.',
      'It says whose set it is. The offer names the number, which matters most on a shared device: if it is not your number, you can see that before carrying on and finishing somebody else\'s work under it. Hiding the number would have been the same disclosure with a wrong record on the end of it.',
      'It does not sit there forever. An unfinished set is forgotten after twelve hours — long enough for a lesson, a break, a bus and a battery, short enough that yesterday\'s set does not surface for whoever picks the device up tomorrow. It is also forgotten the moment a set finishes and its code exists, and one button forgets it on the spot. Forgotten means gone rather than blank.',
      'A set that was left across an update is not picked up. The questions come from the key, the topic and the difficulty, so a release that changes how a question is built changes what sits at that place in the set — and carrying on would mean counting answers to questions that no longer exist.',
      'One thing that was quietly broken and is fixed: pressing through the opening screen went straight to the topics without checking for an unfinished set. The one route a person who had lost their place is most likely to take was the one route that never offered it back. Everything goes through the same check now.',
    ],
    stillMissing: 'nothing is deployed yet, so this all runs from a device that already has it.',
  },
  {
    version: '0.13.0',
    kind: 'ITERATION',
    lines: [
      'There is a real icon now. A conical flask, with the liquid in it drawn as an equals sign.',
      'The flask is the chemistry — it is the one piece of glassware everybody recognises at the size an icon is actually seen. The equals is the maths, and it is the right sign for this in particular: what this teaches is rearranging around an equals sign, using a ratio, moving powers of ten. A plus would have named the one operation the seven topics barely touch, and a flask with a cross on it looks like a first-aid app.',
      'It is a solid shape with the sign cut out of it rather than an outline with a sign inside, because at 32 pixels a solid shape reads and thin lines inside one do not. There is a second version for the phones and tablets that crop an icon to a circle, with the flask kept well inside what survives the crop.',
      'The colours are read from the same file everything else here is coloured from. An icon is the one part of an app that the readability checks cannot reach — it is a picture, not a page — so it was the easiest place for a colour nobody had ever measured to sit unnoticed. It is generated from the palette now, and a check refuses to let the two drift apart.',
    ],
    stillMissing: 'a set closed part-way through is still lost, since the code only exists at the end. Nothing is deployed yet.',
  },
  {
    version: '0.12.0',
    kind: 'CAPABILITY',
    lines: [
      'Codes are read a stack at a time. Paste the whole lot into the box — one per line — and press once. Each gets its own block, in the order they were pasted, headed by the number so it can be found against a list on paper.',
      'A line that does not read stays where it is rather than being dropped, and says what was wrong with it and what was on the line. Underneath there are two counts: how many read and how many did not. Two numbers rather than one over the other, because one over the other reads like a mark out of something.',
      'A number that turns up twice is pointed out and not decided about. It happens when a code is written down twice and it happens when two people were given the same number, and this cannot tell those apart, so it says which line the number appeared on before and leaves it there.',
      'And the moves are added up across the whole stack, ordered by how much went wrong. That is the part worth taking back to the next lesson: it says what to teach again, not who to talk to.',
    ],
    stillMissing: 'the icon is still a simple drawing rather than a proper one, and nothing is deployed yet, so this runs from a device that already has it.',
  },
  {
    version: '0.11.0',
    kind: 'CAPABILITY',
    lines: [
      'A set can be handed in now. If somebody gave you a key and a number, there is a way in from the front screen, and at the end you get a code — sixteen characters in four groups — to give back.',
      'The code says which number you are, how many steps you did, how many were right first time, which kinds of move went wrong and how many times, and roughly how long it took. That is everything in it. No name, nothing you typed, and nothing about the settings you were using: text size, spacing, one step at a time and read-aloud stay on the device, and there is nowhere in a code for them to go. Nobody should have to tell a room something about themselves just by handing work back.',
      'And there is a page for reading them. Whoever set the work opens /teacher, types in the set as they gave it out, and pastes the code. It reads on the device, with no connection and nothing to sign in to, because the page doing the reading is the same code that did the writing.',
      'The characters are chosen for handwriting: there is no I, L, O or U in a code, and if you write O for zero or l for one it still reads. A code from a different key, a different topic or an easier difficulty than the one that was set does not read at all, and the page says which way it is wrong rather than just refusing.',
      'One thing said plainly, because it would be easy to imply otherwise: the check on a code catches a character copied wrong, or last week\'s code, or the wrong set. It cannot stop somebody who reads the source of the page and writes their own — there is no server here, so there is no secret to keep one out. The page says so itself.',
      'A drop-down list on the new page turned out to be painted by the browser rather than by this app: nineteen pixels tall, in system greys that had never been checked for readability in either light or dark. Both are fixed, and the sweep that checks every screen now covers twenty of them rather than fifteen.',
    ],
    stillMissing: 'the icon is still a simple drawing rather than a proper one. Codes are read one at a time, so a stack of thirty is thirty pastes. Nothing is deployed yet, so this all runs from a device that already has it.',
  },
  {
    version: '0.10.0',
    kind: 'CAPABILITY',
    lines: [
      'You can do the arithmetic without leaving the question. Every step that asks for a number now has a scratch line under the answer box, with a keypad, and a button that puts what it worked out straight into the answer.',
      'The keypad is there because this gets used on a tablet by finger, and × and ÷ are two keyboard layers away on most of them — far enough that you would reach for a phone instead, which is exactly the thing worth avoiding. There is an EE key for the powers of ten, since a mole is 6.022 × 10²³ and nobody types twenty-three zeros. It takes typed input too if you have a keyboard.',
      'It does not round, and that is deliberate. Working out how many figures an answer is entitled to is one of the seven things this teaches. A scratch line that quietly handed back 90.3 would be doing that step for you at the exact moment you were being asked to do it, so it hands back the whole number and says to round it yourself.',
      'It also never sees the question. It multiplies the numbers you chose in the order you chose them — deciding what to multiply, and which way up, is the whole of what this is for and the scratch line has no part in it. The description in the ⓘ panel used to say this is not a calculator; it now says what is actually true, which is that it does not solve the question for you.',
    ],
    stillMissing: 'nothing can be handed in and there is still no page for whoever set the work. The icon is still a simple drawing rather than a proper one.',
  },
];
