/**
 * icon.mjs — the icons, generated from the palette rather than drawn beside it.
 *
 * ## Why this is generated
 *
 * An icon is **the one surface the accessibility gate cannot reach**. It is not
 * in the document, so nothing reverse-maps its colours to a token and nothing
 * measures its contrast. That makes it the easiest place in the whole
 * application for an unmeasured colour to appear and stay.
 *
 * So the colours are not written here. They are read from
 * `palettes/solve-ent.json` — the same file the hub's palette gate measures and
 * the same file `tools/palette.mjs` generates the CSS tokens from. The palette
 * moving and the icon not moving is a drift this closes by construction.
 *
 * ## The mark
 *
 * An Erlenmeyer flask, with the liquid in it drawn as an EQUALS SIGN.
 *
 * The flask is the chemistry, and it is the one piece of glassware everybody
 * recognises at 32 pixels. The equals is the maths, and it is the right operator
 * for this application specifically: what it teaches is rearranging around an
 * equals sign, using a ratio, moving powers of ten. A plus sign would name the
 * one operation the seven topics barely touch.
 *
 * **A SOLID SILHOUETTE WITH THE SIGN KNOCKED OUT**, rather than an outline with
 * a sign inside it. At the size this is actually seen — a home screen, a tab
 * strip — a solid shape reads first and thin interior strokes turn to mush.
 *
 *   node tools/icon.mjs           # write both icons
 *   node tools/icon.mjs --check   # fail if what is committed has drifted
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

const palette = JSON.parse(readFileSync(join(REPO, 'palettes/solve-ent.json'), 'utf8'));
const night = palette['solvent-night'];

/**
 * NIGHT, ALWAYS, whichever mode the device is in.
 *
 * An icon sits on somebody else's wallpaper and cannot know what is behind it,
 * so it carries its own ground rather than borrowing one. Night is the darker
 * of this palette's two pages and the accent on it is the pairing with the most
 * room — the same reasoning the placeholder was drawn under, now written where
 * the values are read rather than beside where they were typed.
 */
const GROUND = night.page;
const MARK = night.accents.primary;

/**
 * The flask, as one polygon that is filled AND stroked in the same colour.
 *
 * The stroke is what rounds the corners: `stroke-linejoin: round` on a filled
 * polygon softens every join and fattens the silhouette evenly, which is a
 * rounded flask in six points rather than a path with a dozen arcs in it that
 * nobody can adjust later.
 */
const FLASK = '218,130 294,130 294,206 378,356 134,356 218,206';
const LIP = { x1: 198, x2: 314, y: 130 };

/** The equals sign, knocked out of the liquid in the ground colour. */
const BARS = [
  { y: 267, width: 132, height: 26 },
  { y: 313, width: 132, height: 26 },
];

const bar = (b) =>
  `<rect x="${String(256 - b.width / 2)}" y="${String(b.y)}" width="${String(b.width)}" ` +
  `height="${String(b.height)}" rx="${String(b.height / 2)}" fill="${GROUND}"/>`;

const mark = () =>
  [
    `<polygon points="${FLASK}" fill="${MARK}" stroke="${MARK}" stroke-width="24" stroke-linejoin="round"/>`,
    `<path d="M${String(LIP.x1)} ${String(LIP.y)}H${String(LIP.x2)}" stroke="${MARK}" stroke-width="26" stroke-linecap="round"/>`,
    ...BARS.map(bar),
  ].join('\n    ');

const HEADER = `<!-- GENERATED by tools/icon.mjs from palettes/solve-ent.json. Do not edit here.
       An icon is the one surface the accessibility gate cannot reach, so its
       colours are READ from the file that gate measures rather than typed. -->`;

const any = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" role="img" aria-label="Solve-ent">
  ${HEADER}
  <rect width="512" height="512" rx="112" fill="${GROUND}"/>
  <g>
    ${mark()}
  </g>
</svg>
`;

// MASKABLE: the platform crops this to whatever shape it likes, so the mark is
// scaled into the safe circle — 80% of the width, centred — and the ground goes
// corner to corner. A mark that merely FITS the square is a mark with its base
// sliced off on a device that crops to a circle.
const SCALE = 0.78;
const OFFSET = 256 * (1 - SCALE);
const maskable = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" role="img" aria-label="Solve-ent">
  ${HEADER}
  <rect width="512" height="512" fill="${GROUND}"/>
  <g transform="translate(${String(OFFSET)} ${String(OFFSET)}) scale(${String(SCALE)})">
    ${mark()}
  </g>
</svg>
`;

const files = [
  ['public/icon.svg', any],
  ['public/icon-maskable.svg', maskable],
];

console.log('\n=== the icons, from the palette · Solve-ent ===\n');

let drifted = 0;
for (const [path, wanted] of files) {
  const full = join(REPO, path);
  if (CHECK) {
    let have = '';
    try {
      have = readFileSync(full, 'utf8');
    } catch {
      have = '';
    }
    if (have !== wanted) {
      console.log(`  FAIL  ${path} has drifted from the palette it is generated from`);
      drifted += 1;
    } else {
      console.log(`  ok    ${path} matches the palette`);
    }
  } else {
    writeFileSync(full, wanted);
    console.log(`  ok    wrote ${path}`);
  }
}

if (CHECK && drifted > 0) {
  console.log('\nThe palette moved and the icons did not. Run: node tools/icon.mjs\n');
  process.exit(1);
}
console.log(`\nThe ground is ${GROUND} and the mark is ${MARK}, both read from the palette.\n`);
