#!/usr/bin/env node
/**
 * pwa.mjs — the service worker and the manifest, generated from one source.
 *
 *   node tools/pwa.mjs           write public/sw.js and public/manifest.webmanifest
 *   node tools/pwa.mjs --check   fail if either has drifted
 *
 * ## Why generated rather than written
 *
 * Two things in a service worker must move with the release and are exactly the
 * things a hand-edited file gets wrong:
 *
 * **The cache name.** If it does not change, a new release reuses the old cache
 * and can never replace what is already in it. Everyone who has the app keeps
 * the old shell forever, and the app cannot notice — that is what caching means
 * (hub LESSONS §21). `tools/version-check.mjs` holds the name to the triplet;
 * this is what makes it true without anybody remembering.
 *
 * **The precache list.** Written by hand it goes stale the first time a module
 * is added, and the symptom is a file that silently is not there offline. Here
 * it is READ OFF THE TREE, so what the worker caches and what the site contains
 * cannot differ.
 *
 * ## What the worker deliberately does NOT do
 *
 * It does not call `skipWaiting()` during install. That is the default advice
 * and it is the thing that makes staleness actively harmful: the new worker
 * takes over under the OPEN page, which is still running the previous release's
 * HTML and modules, and `activate` deletes the old cache — so that page is
 * served NEW files from then on. Old markup, new modules, no reload, nothing
 * said. It happened in two sibling apps, for twenty-two releases in one of them.
 *
 * So the new version WAITS, the reader is told in words, and `skipWaiting()`
 * happens only on a message from the page — which is to say, on the reader's
 * decision (Doctrine §7h.1).
 */

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = dirname(dirname(fileURLToPath(import.meta.url)));
const PUBLIC = join(REPO, 'public');
const SW = join(PUBLIC, 'sw.js');
const MANIFEST = join(PUBLIC, 'manifest.webmanifest');

const versionSource = readFileSync(join(REPO, 'src/version.ts'), 'utf8');
const VERSION = /export const VERSION = '([^']+)'/.exec(versionSource)?.[1];
const APP_NAME = /export const APP_NAME = '([^']+)'/.exec(versionSource)?.[1];
if (VERSION === undefined || APP_NAME === undefined) {
  console.error('src/version.ts does not export a VERSION and an APP_NAME this can read.');
  process.exit(1);
}

const palette = JSON.parse(readFileSync(join(REPO, 'palettes/solve-ent.json'), 'utf8'));

/**
 * Everything the site is made of, read off the tree.
 *
 * TWO EXCLUSIONS, and both are about this file's own output.
 *
 * The worker itself, because a worker that caches itself serves its own old
 * copy and can never be replaced — the staleness bug, in the one file that
 * exists to fix it.
 *
 * And the manifest, which this generator WRITES. Reading it back off the tree
 * made the output depend on whether a previous run had happened: the first run
 * produced a list without it, the second produced a list with it, and the drift
 * check failed until the generator had been run twice. A generator whose output
 * is part of its own input is not a generator, it is a fixed-point search — so
 * the manifest is added to the list by NAME instead, which is true whether or
 * not it exists yet.
 */
const GENERATED = ['/sw.js', '/manifest.webmanifest'];

function siteFiles() {
  const out = [];
  const walk = (dir) => {
    for (const name of readdirSync(dir).sort()) {
      if (name.startsWith('.')) continue;
      const full = join(dir, name);
      if (statSync(full).isDirectory()) walk(full);
      else out.push(`/${relative(PUBLIC, full).split('\\').join('/')}`);
    }
  };
  walk(PUBLIC);
  return [...out.filter((p) => !GENERATED.includes(p)), '/manifest.webmanifest'].sort();
}

const files = siteFiles();
// `/` and `/whats-new` are what a reader types or lands on; the files behind
// them are `/index.html` and `/whats-new/index.html`. Both forms are cached, or
// the app works offline only for somebody who typed the filename.
const routes = ['/', '/whats-new'];
const precache = [...new Set([...routes, ...files])].sort();

const sw = `/* sw.js — GENERATED by tools/pwa.mjs. Do not edit here.
 *
 * The cache name carries ${VERSION}, and it is generated rather than typed
 * because a cache name that does not move with the release means everyone who
 * already has the app keeps the old shell forever — and the app cannot notice,
 * which is what caching means.
 *
 * The precache list is read off the tree for the same reason: written by hand it
 * goes stale the first time a module is added, and the symptom is a file that
 * silently is not there offline.
 *
 * Regenerate: node tools/pwa.mjs
 */

const CACHE_NAME = 'solvent-${VERSION}';

const PRECACHE = [
${precache.map((p) => `  '${p}',`).join('\n')}
];

self.addEventListener('install', (event) => {
  // NO skipWaiting() HERE, and that is Doctrine §7h.1 rather than an oversight.
  // Taking over during install puts the new worker under the OPEN page, which is
  // still running the previous release's HTML and modules — and activate deletes
  // the old cache, so that page is served NEW files from then on. Old markup,
  // new modules, no reload, nothing said. The reader's decision releases it
  // instead; see the message handler below.
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) => Promise.all(names.filter((name) => name !== CACHE_NAME).map((name) => caches.delete(name))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  // THE READER'S DECISION. Waiting without a way out is never arriving, so the
  // page posts this when somebody presses the control in the update strip.
  if (event.data === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // A navigation falls back to the cached page for that route, so a reader who
  // opens the app with no connection gets the app rather than a browser error.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() =>
        caches.match(url.pathname).then((hit) => hit ?? caches.match('/')).then((hit) => hit ?? Response.error()),
      ),
    );
    return;
  }

  event.respondWith(
    caches.match(request).then((hit) => {
      if (hit !== undefined) return hit;
      return fetch(request);
    }),
  );
});
`;

const manifest = {
  name: `${APP_NAME} — the algebra a chemistry problem needs`,
  short_name: APP_NAME,
  description:
    'Practice for the specific algebra moves a chemistry calculation needs. ' +
    'It works out which mistake produces a wrong answer, and says so.',
  start_url: '/',
  scope: '/',
  display: 'standalone',
  orientation: 'any',
  background_color: palette['solvent-night'].page,
  theme_color: palette['solvent-night'].page,
  icons: [
    { src: '/icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
    { src: '/icon-maskable.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'maskable' },
  ],
  lang: 'en',
};
const manifestText = `${JSON.stringify(manifest, null, 2)}\n`;

if (process.argv.includes('--check')) {
  const failures = [];
  const compare = (path, want, label) => {
    if (!existsSync(path)) {
      failures.push(`${label} is missing. Run: node tools/pwa.mjs`);
      return;
    }
    if (readFileSync(path, 'utf8') !== want) failures.push(`${label} has drifted from its source`);
  };
  compare(SW, sw, 'public/sw.js');
  compare(MANIFEST, manifestText, 'public/manifest.webmanifest');

  // THE PRECACHE LIST AGAINST THE TREE, read off the generated text rather than
  // trusted to the generator — a drift check regenerates from the same generator
  // and compares like with like, so it cannot catch a generator that stopped
  // listing something (hub LESSONS §156).
  const listed = [...sw.matchAll(/^ {2}'([^']+)',$/gm)].map((m) => m[1]);
  for (const file of files) {
    if (!listed.includes(file)) failures.push(`${file} is in public/ and the worker does not cache it`);
  }
  for (const route of routes) {
    if (!listed.includes(route)) failures.push(`the worker does not cache the route ${route}`);
  }
  if (listed.includes('/sw.js')) {
    failures.push('the worker caches ITSELF, so it would serve its own old copy and could never be replaced');
  }

  console.log('\n=== offline, and saying so · Solve-ent ===\n');
  if (failures.length === 0) {
    console.log(`  ok    the cache is named solvent-${VERSION}, so a release cannot reuse the last one`);
    console.log(`  ok    ${listed.length} path(s) precached, read off the tree rather than typed`);
    console.log('  ok    the worker does not cache itself');
    console.log('  ok    public/sw.js and public/manifest.webmanifest match their source');
    console.log('\nA new version waits; the reader decides when to take it.\n');
    process.exit(0);
  }
  for (const failure of failures) console.log(`  FAIL  ${failure}`);
  console.error('\nRun: node tools/pwa.mjs\n');
  process.exit(1);
}

writeFileSync(SW, sw);
writeFileSync(MANIFEST, manifestText);
console.log(`wrote public/sw.js (cache solvent-${VERSION}, ${precache.length} paths) and public/manifest.webmanifest`);
