/**
 * social-card.mjs — the GitHub social preview, generated from the palette.
 *
 * 1280x640 (2:1), which is what GitHub crops to. It is the card that appears
 * when the repository is linked anywhere, so it is the one image most people
 * see before they see the app.
 *
 * ## Why it is generated
 *
 * Same reason as the icon: **the colours are read from
 * `palettes/solve-ent.json`**, the file the hub's palette gate measures. A card
 * with hand-picked colours is a second palette nobody is checking, on the most
 * public surface this repository has.
 *
 * The mark is the app's own icon, inlined from `public/icon.svg` rather than
 * redrawn — one flask, not two that drift.
 *
 * ## Why the words are the ones in METADATA.md
 *
 * The card says what the repository description says. Two sentences about what
 * this is, written once, in the file where the description is proposed and
 * applied. A card that said something else would be a third description.
 *
 *   node tools/social-card.mjs        # write the html and render the png
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const palette = JSON.parse(readFileSync(join(REPO, 'palettes/solve-ent.json'), 'utf8'));
const night = palette['solvent-night'];

/**
 * The mark, taken from the icon this app actually ships.
 *
 * WITHOUT ITS OWN GROUND. The icon carries a rounded tile because it sits on
 * somebody's wallpaper and cannot know what is behind it; here it is on this
 * card's gradient, and leaving the tile in drew a visible dark square around
 * the flask. So the background rect is stripped and the flask sits on the card.
 */
const icon = readFileSync(join(REPO, 'public/icon.svg'), 'utf8')
  .replace(/<!--[\s\S]*?-->/g, '')
  .replace(/<rect[^>]*rx="112"[^>]*\/>/, '')
  .replace('<svg ', '<svg width="188" height="188" ');

/**
 * The words. THE SAME TWO SENTENCES AS THE REPOSITORY DESCRIPTION — the card
 * and the description are one claim, and a card that said something else would
 * be a third place to keep in step.
 */
const HEADLINE = 'Learn the algebra chemistry needs.';
const TAGLINE = 'Every wrong answer is traced to the mistake that produced it, not marked wrong.';

/**
 * WHAT IT PROMISES, and every one of these is true today rather than intended.
 * "No student data" is the one worth the space: it is the claim this
 * application is built around, and it is the one a school actually asks about.
 */
const CHIPS = ['Free', 'No account', 'Works offline', 'No student data'];

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<!-- GENERATED by tools/social-card.mjs from palettes/solve-ent.json and
     public/icon.svg. Do not edit here. 1280x640, which is what GitHub crops to. -->
<style>
  :root{
    --page:${night.page}; --page-alt:${night.pageAlt};
    --surface:${night.surfaces[1]}; --rail:${night.hairline};
    --text:${night.text[0]}; --muted:${night.text[2]};
    --accent:${night.accents.primary};
  }
  *{box-sizing:border-box;margin:0;padding:0}
  html,body{width:1280px;height:640px}
  body{
    background:
      radial-gradient(1100px 700px at 82% -16%, ${night.surfaces[0]} 0%, rgba(0,0,0,0) 64%),
      linear-gradient(180deg,var(--page-alt),var(--page));
    color:var(--text);
    font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
    -webkit-font-smoothing:antialiased;
    display:flex;align-items:center;gap:64px;
    padding:0 104px;position:relative;overflow:hidden;
  }
  .mark{flex:0 0 auto;line-height:0}
  .words{flex:1 1 auto}
  .name{font-size:30px;font-weight:640;letter-spacing:0.12em;text-transform:uppercase;color:var(--accent)}
  h1{font-size:64px;font-weight:660;letter-spacing:-0.022em;line-height:1.05;margin-top:16px}
  .rule{width:132px;height:6px;border-radius:6px;margin:28px 0 24px;background:var(--accent)}
  .tag{font-size:29px;color:var(--muted);line-height:1.34;max-width:760px}
  .chips{display:flex;gap:12px;margin-top:38px;flex-wrap:wrap}
  .chip{
    font-size:21px;font-weight:600;letter-spacing:0.015em;
    color:var(--text);background:var(--surface);border:1px solid var(--rail);
    border-radius:999px;padding:11px 22px;
  }
  .foot{position:absolute;right:104px;bottom:52px;font-size:21px;color:var(--muted);letter-spacing:0.04em}
</style>
</head>
<body>
  <div class="mark">${icon.trim()}</div>
  <div class="words">
    <div class="name">Solve-ent</div>
    <h1>${HEADLINE}</h1>
    <div class="rule"></div>
    <p class="tag">${TAGLINE}</p>
    <div class="chips">${CHIPS.map((c) => `<span class="chip">${c}</span>`).join('')}</div>
  </div>
  <div class="foot">solve-ent.pages.dev</div>
</body>
</html>
`;

writeFileSync(join(REPO, 'social-card.html'), html);
console.log('\n=== the social preview · Solve-ent ===\n');
console.log('  ok    wrote social-card.html from the palette and the shipped icon');

const { chromium } = await import('playwright');
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 640 }, deviceScaleFactor: 1 });
await page.goto(`file://${join(REPO, 'social-card.html')}`);
await page.waitForTimeout(250);
await page.screenshot({ path: join(REPO, 'social-preview.png') });
await browser.close();
console.log('  ok    rendered social-preview.png at 1280x640, the size GitHub crops to');
console.log(`\nThe ground is ${night.page} and the mark is ${night.accents.primary}, both read from the palette.\n`);
